language: ruby
cache: bundler
bundler_args: --without development
sudo: false

rvm:
  - 2.5
  - 2.6
  - 2.7
  - jruby
  - rbx

gemfile:
  - gemfiles/activerecord_2.3.gemfile
  - gemfiles/activerecord_3.2.gemfile
  - gemfiles/activerecord_4.2.gemfile
  - gemfiles/activerecord_5.2.gemfile
  - gemfiles/activerecord_6.0.gemfile
  - gemfiles/activerecord_master.gemfile

matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby
    - rvm: rbx
    - gemfile: gemfiles/activerecord_master.gemfile
  exclude:
    - rvm: 2.5
      gemfile: gemfiles/activerecord_2.3.gemfile
    - rvm: 2.5
      gemfile: gemfiles/activerecord_3.2.gemfile
    - rvm: 2.6
      gemfile: gemfiles/activerecord_2.3.gemfile
    - rvm: 2.6
      gemfile: gemfiles/activerecord_3.2.gemfile
    - rvm: 2.7
      gemfile: gemfiles/activerecord_2.3.gemfile
    - rvm: 2.7
      gemfile: gemfiles/activerecord_3.2.gemfile
    - rvm: 2.7
      gemfile: gemfiles/activerecord_4.2.gemfile
